import { Redis } from '@upstash/redis'
import seed from './seed-repos.json'

export const ORGS = ['exasol', 'exasol-labs']
const CATALOG_KEY = 'exasol:catalog'

// ---- Categorization (kept in sync with the original generator) --------------

const CATS = [
  ['Drivers & Connectivity', ['driver', 'pyexasol', 'odbc', 'jdbc', 'dbapi', 'connector', '-go', 'websocket', 'exaplus', 'exarrow', 'bucketfs-java', 'bucketfs-client', 'bucketfs-python', 'hamcrest', 'telemetry-java']],
  ['Virtual Schemas', ['virtual-schema', 'virtual_schema', 'adapter', 'edml', 'row-level-security']],
  ['BI & Data Engineering', ['dbt', 'sqlalchemy', 'spark', 'kafka', 'powerbi', 'tableau', 'looker', 'etl', 'airflow', 'metabase', 'jaffle', 'azure-data-factory']],
  ['AI / ML / Agentic', ['ai-', '-ai', 'mcp', 'machine', 'data-science', 'science', 'sagemaker', 'transformer', 'llm', 'sklearn', 'agent', 'text2sql', 'mlflow', 'semantic', 'process-mining', 'keyphrase', 'vectorizer', 'metadata-agent']],
  ['UDF & Script Languages', ['script-language', 'udf', 'slc', 'language-container', 'import-export-udf', 'python-extension-common']],
  ['Testing', ['test', 'testcontainer', 'mock', 'itde', 'database-cleaner', 'version-number-provider', 'version-getter']],
  ['Build / CI / Tooling', ['toolbox', 'project-keeper', 'release-droid', 'error-reporting', 'error-code', 'error-catalog', 'error-crawler', 'maven', 'artifact-reference', 'quality-summarizer', 'serial-version', 'sphinx', 'pre-commit', 'autogenerated-resource']],
  ['Cloud & Deployment', ['terraform', 'docker', 'kubernetes', 'operator', 'cloud', 'aws', 'saas', 'helm', 'ansible', 'nagios', 'cloudformation', 'cloudwatch', 'local-vm', 'extension-manager', 'extension-parameter']],
  ['Docs / Examples / Solutions', ['doc', 'example', 'solution', 'tutorial', 'demo', 'sample', 'styleguide', 'style-guide', 'knowledgebase', 'benchkit', 'opendata', 'sports']],
]

function categorize(repo) {
  const haystack = `${repo.name} ${repo.description || ''} ${(repo.topics || []).join(' ')}`.toLowerCase()
  for (const [name, kws] of CATS) {
    if (kws.some((k) => haystack.includes(k))) return name
  }
  return 'Core / Other'
}

function normalize(r) {
  const repo = {
    name: r.name,
    org: r.owner.login,
    full_name: r.full_name,
    description: r.description || '',
    language: r.language || 'Other',
    stars: r.stargazers_count ?? 0,
    forks: r.forks_count ?? 0,
    archived: !!r.archived,
    is_fork: !!r.fork,
    topics: Array.isArray(r.topics) ? r.topics : [],
    url: r.html_url,
    homepage: r.homepage || '',
    pushed_at: (r.pushed_at || '').slice(0, 10),
    updated_at: (r.updated_at || '').slice(0, 10),
    created_at: (r.created_at || '').slice(0, 10),
    open_issues: r.open_issues_count ?? 0,
    license: r.license?.spdx_id ?? null,
  }
  repo.category = categorize(repo)
  return repo
}

// ---- GitHub fetch -----------------------------------------------------------

async function fetchOrgRepos(org) {
  const headers = {
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': 'exasol-repo-explorer',
  }
  if (process.env.GITHUB_TOKEN) headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`

  const all = []
  for (let page = 1; page <= 6; page++) {
    const url = `https://api.github.com/orgs/${org}/repos?per_page=100&page=${page}&type=public`
    const res = await fetch(url, { headers, cache: 'no-store' })
    if (!res.ok) {
      const body = await res.text()
      throw new Error(`GitHub ${org} page ${page}: ${res.status} ${body.slice(0, 200)}`)
    }
    const batch = await res.json()
    if (!Array.isArray(batch) || batch.length === 0) break
    all.push(...batch)
    if (batch.length < 100) break
  }
  return all
}

export async function fetchFromGitHub() {
  const raw = (await Promise.all(ORGS.map(fetchOrgRepos))).flat()
  const seen = new Map()
  for (const r of raw) seen.set(r.full_name, r)
  const repos = [...seen.values()]
    .map(normalize)
    .sort((a, b) => b.stars - a.stars || a.name.localeCompare(b.name))
  return repos
}

// ---- Redis (Upstash) cache --------------------------------------------------

function getRedis() {
  const url = process.env.UPSTASH_REDIS_REST_URL || process.env.KV_REST_API_URL
  const token = process.env.UPSTASH_REDIS_REST_TOKEN || process.env.KV_REST_API_TOKEN
  if (!url || !token) return null
  return new Redis({ url, token })
}

const SEED_CATALOG = {
  repos: seed,
  refreshedAt: null,
  source: 'seed',
}

/** Read the catalog: Redis if available, else the bundled snapshot. Never throws. */
export async function readCatalog() {
  const redis = getRedis()
  if (!redis) return SEED_CATALOG
  try {
    const data = await redis.get(CATALOG_KEY)
    if (data && Array.isArray(data.repos) && data.repos.length) {
      return { ...data, source: 'redis' }
    }
  } catch (e) {
    console.error('readCatalog redis error:', e?.message)
  }
  return SEED_CATALOG
}

/** Fetch fresh data from GitHub and write it to Redis. Returns the new catalog. */
export async function refreshCatalog() {
  const repos = await fetchFromGitHub()
  const catalog = { repos, refreshedAt: new Date().toISOString(), source: 'github' }
  const redis = getRedis()
  let persisted = false
  if (redis) {
    await redis.set(CATALOG_KEY, catalog)
    persisted = true
  }
  return { ...catalog, persisted }
}
